apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-rabbitmq-operator
  namespace: contrail
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tf-rabbitmq-operator
  template:
    metadata:
      labels:
        name: tf-rabbitmq-operator
    spec:
      nodeSelector:
          node-role.kubernetes.io/master: ''
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      hostNetwork: true
      serviceAccountName: tf-rabbitmq-operator
      containers:
        - name: tf-rabbitmq-operator
          # Replace this with the built image name
          image: docker.io/michaelhenkel/rabbitmq-tf-operator:v0.0.1
          command:
          - tf-rabbitmq-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "tf-rabbitmq-operator"
